spring:
  application:
    name: xlei-ai-platform
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    # 阿里云百炼平台配置
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max # 模型名称，可更改 https://help.aliyun.com/zh/model-studio/getting-started/models
          temperature: 0.8 # 模型温度，值越大，输出结果越随机
      # 引入百炼平台的 通用文本向量-v3模型
      embedding:
        options:
          model: text-embedding-v3
          # 向量维度
          dimensions: 1024
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: 192.168.150.101
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job_train?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456
logging:
  level:
    org.springframework.ai: debug
    com.xlei.aiplatform: debug

